services:
  - type: web
    name: eoccurrence
    runtime: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn eoccurrence.wsgi:application

    postDeployCommand: python manage.py migrate

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eoccurrence.settings

      - key: SECRET_KEY
        generateValue: true

      - key: PYTHON_VERSION
        value: 3.10
      
      - key: DATABASE_URL
        value: postgresql://eoccurrence_db_user:T5zywbumTCRAfDf8CAXLevpwRJTr89U9@dpg-d4k90e8dl3ps73dfg22g-a/eoccurrence_db